<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IcfesQA.CLI</RootNamespace>
    <AssemblyName>icfes-qa</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IcfesQA.Core\IcfesQA.Core.csproj" />
  </ItemGroup>
</Project>
